### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ishymko** [rajbos/Stryker.MultipleProjectRunner#1]
Hi, @rajbos,

Thanks for this workaround!

Could you please add a license into the repo to make it clear for the potential users? By default (if no license is provided) reusing is not allowed: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license (see the second paragraph).

Thanks

**Comment by rajbos** [comment]
Great point @vanashimko ! Will do so. 
Are you working with this work around already?

**Comment by ishymko** [comment]
Thanks! Not yet. I am still figuring out how to approach running stryker on a build server, but already started thinking about running against the whole solution and found your blog post, which brought me into this repo 😄

**Comment by rajbos** [comment]
Wonderful! Good luck with settings things up 👍 .
