### ISSUE TITLE
Error on arguments supplied

### ISSUE THREAD

**Issue by LeonWinstanley** [rajbos/Stryker.MultipleProjectRunner#3]
It seems like the `Run Stryker.ps1` file has come a little out of date with the current dotnet tool in terms of the arguments supplied. 

I'm not a huge player in the open-source community but happy to offer a small pr for this fix, but a note for anyone having this project it's easily fixed by changing line 8 in `Run Strker.ps1` 

from:
`dotnet stryker --project-file "$csprojPath" --solution-path $solutionPath --reporters "['json', 'progress']"`

to:
`dotnet stryker --project "$csprojPath" --solution $solutionPath --reporter "json" --reporter "progress"`

**Comment by rajbos** [comment]
Thanks for letting me know @LeonWinstanley 👍. I'll happily add it somewhere next week, but feel free to send in a PR with that fix 🙌.

**Comment by rajbos** [comment]
Fixed in #6
